# Desafio do Oráculo Preditivo
## Ecommerce Customers

### Grupo 01

- Apolo Bastos
- Nicolas Gabriel
- Caio Simonassi
- Gabriel Nito
- Jônatas

## 1. Introdução e Contextualização

Este projeto utiliza o dataset Ecommerce Customers para estudar um problema de regressão relacionado ao comportamento de clientes de um e-commerce. Nesta etapa inicial, o foco está em conhecer a estrutura dos dados disponibilizados, sem definir ainda a variável-alvo ou qualquer estratégia de modelagem.

## 2. Objetivo do Projeto

O objetivo final do trabalho será comparar diferentes abordagens de regressão para prever uma variável contínua. Por enquanto, estamos apenas realizando o carregamento e a inspeção inicial dos dados, deixando a Análise Exploratória de Dados e as etapas de modelagem para depois.

## 3. Importação das Bibliotecas

Nesta etapa, a única biblioteca necessária é o pandas, que será utilizado para carregar e inspecionar o arquivo de dados.

In [1]:
import pandas as pd

## 4. Carregamento do Dataset

O arquivo foi mantido com o nome real disponibilizado pelo dataset. Como esta célula deve ser executada a partir da pasta `notebooks/`, o caminho relativo aponta para `../data/Ecommerce Customers`.

In [2]:
arquivo_dataset = "../data/Ecommerce Customers"
df = pd.read_csv(arquivo_dataset)

print("DataFrame criado com sucesso.")
print(f"Arquivo carregado: {arquivo_dataset}")

DataFrame criado com sucesso.
Arquivo carregado: ../data/Ecommerce Customers

## 5. Inspeção Inicial dos Dados

A inspeção inicial ajuda a verificar o conteúdo, o tamanho, a estrutura e a qualidade básica do dataset antes de qualquer decisão de pré-processamento ou modelagem.

### 5.1 Primeiras linhas

A visualização das primeiras linhas permite conferir exemplos dos registros e observar como as colunas estão organizadas no DataFrame.

In [3]:
df.head()

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092

### 5.2 Dimensões do dataset

A propriedade `shape` informa a quantidade de linhas e colunas presentes no DataFrame.

In [4]:
quantidade_linhas, quantidade_colunas = df.shape
print(f"Quantidade de linhas: {quantidade_linhas}")
print(f"Quantidade de colunas: {quantidade_colunas}")

Quantidade de linhas: 500
Quantidade de colunas: 8

### 5.3 Estrutura e tipos de dados

O método `info()` apresenta um resumo da estrutura do DataFrame, incluindo a quantidade de entradas, as colunas, os tipos de dados e a presença de valores não nulos.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Email                 500 non-null    str
 1   Address               500 non-null    str
 2   Avatar                500 non-null    str
 3   Avg. Session Length   500 non-null    float64
 4   Time on App           500 non-null    float64
 5   Time on Website       500 non-null    float64
 6   Length of Membership  500 non-null    float64
 7   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5), str(3)
memory usage: 31.4 KB

Os tipos das colunas também podem ser observados em uma tabela para facilitar a leitura.

In [6]:
df.dtypes.to_frame(name="Tipo de dado")

                     Tipo de dado
Email                         str
Address                       str
Avatar                        str
Avg. Session Length       float64
Time on App               float64
Time on Website           float64
Length of Membership      float64
Yearly Amount Spent       float64

### 5.4 Identificação das variáveis

A tabela a seguir reúne o nome de cada coluna, o tipo identificado pelo pandas e uma classificação preliminar como numérica ou categórica/textual. Essa classificação apenas descreve o que está presente no arquivo; nenhuma decisão sobre uso no modelo é tomada nesta etapa.

In [7]:
classificacoes = [
    "numérica" if pd.api.types.is_numeric_dtype(tipo) else "categórica/textual"
    for tipo in df.dtypes
]

tabela_variaveis = pd.DataFrame({
    "Nome da coluna": df.columns,
    "Tipo de dado": df.dtypes.astype(str).values,
    "Classificação preliminar": classificacoes,
})

tabela_variaveis

         Nome da coluna Tipo de dado Classificação preliminar
0                 Email          str       categórica/textual
1               Address          str       categórica/textual
2                Avatar          str       categórica/textual
3   Avg. Session Length      float64                 numérica
4           Time on App      float64                 numérica
5       Time on Website      float64                 numérica
6  Length of Membership      float64                 numérica
7   Yearly Amount Spent      float64                 numérica

### 5.5 Valores ausentes

A soma de valores nulos por coluna oferece uma verificação inicial de dados ausentes. Nenhum tratamento será realizado agora.

In [8]:
valores_ausentes = df.isnull().sum()
valores_ausentes.to_frame(name="Quantidade de valores ausentes")

                      Quantidade de valores ausentes
Email                                              0
Address                                            0
Avatar                                             0
Avg. Session Length                                0
Time on App                                        0
Time on Website                                    0
Length of Membership                               0
Yearly Amount Spent                                0

Na inspeção realizada, não foram identificados valores nulos no dataset. O tratamento de valores ausentes permanece fora do escopo desta etapa.

### 5.6 Registros duplicados

A verificação abaixo conta as linhas completamente duplicadas. Nenhum registro será removido nesta etapa.

In [9]:
quantidade_duplicatas = df.duplicated().sum()
print(f"Quantidade de registros duplicados: {quantidade_duplicatas}")

Quantidade de registros duplicados: 0

A inspeção inicial não encontrou linhas completamente duplicadas no dataset. A análise de duplicatas está encerrada sem alterar os dados.

## 6. Observações Iniciais

Com base apenas na inspeção realizada, o dataset contém 500 registros e 8 variáveis. Não foram identificados valores ausentes nem linhas completamente duplicadas. Há cinco variáveis numéricas e três variáveis categóricas/textuais. A definição da variável-alvo e as decisões de Análise Exploratória de Dados e modelagem ficarão para as próximas etapas do projeto.